name: rec_system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23
  - pandas=1.5
  - matplotlib=3.7
  - scipy=1.10
  - scikit-learn=1.2
  - seaborn=0.12
  - tqdm=4.65
  - ipykernel=6.22
  - pyarrow=12.0
  - jupyter
  - notebook
  - ipywidgets
  - pip
  - pip:
    - scikit-surprise==1.1.3