name: surprise_env
channels:
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - scipy
  - pandas
  - numpy
  - scikit-surprise
  - ipykernel
  - seaborn
  - tqdm
  - scikit-learn
  - pyarrow
prefix: C:\Users\yuric\anaconda3\envs\surprise_env
