name: ml_pytorch
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-surprise
  - pytorch=2.1.*         
  - ipython
  - notebook
  - ipykernel
  - widgetsnbextension
  - bar_chart_race        
  - wordcloud             
  - pip                   
